// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/parking-lot-history.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/bayu-gara/parking-lot/internal/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockParkingLotHistoryRepository is a mock of ParkingLotHistoryRepository interface.
type MockParkingLotHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParkingLotHistoryRepositoryMockRecorder
}

// MockParkingLotHistoryRepositoryMockRecorder is the mock recorder for MockParkingLotHistoryRepository.
type MockParkingLotHistoryRepositoryMockRecorder struct {
	mock *MockParkingLotHistoryRepository
}

// NewMockParkingLotHistoryRepository creates a new mock instance.
func NewMockParkingLotHistoryRepository(ctrl *gomock.Controller) *MockParkingLotHistoryRepository {
	mock := &MockParkingLotHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockParkingLotHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingLotHistoryRepository) EXPECT() *MockParkingLotHistoryRepositoryMockRecorder {
	return m.recorder
}

// FindLastParkingHistoryByVehicleNumber mocks base method.
func (m *MockParkingLotHistoryRepository) FindLastParkingHistoryByVehicleNumber(ctx context.Context, vehicleNumber string) (model.ParkingLotHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastParkingHistoryByVehicleNumber", ctx, vehicleNumber)
	ret0, _ := ret[0].(model.ParkingLotHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastParkingHistoryByVehicleNumber indicates an expected call of FindLastParkingHistoryByVehicleNumber.
func (mr *MockParkingLotHistoryRepositoryMockRecorder) FindLastParkingHistoryByVehicleNumber(ctx, vehicleNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastParkingHistoryByVehicleNumber", reflect.TypeOf((*MockParkingLotHistoryRepository)(nil).FindLastParkingHistoryByVehicleNumber), ctx, vehicleNumber)
}

// Insert mocks base method.
func (m *MockParkingLotHistoryRepository) Insert(ctx context.Context, parkingLotHistory model.ParkingLotHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, parkingLotHistory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockParkingLotHistoryRepositoryMockRecorder) Insert(ctx, parkingLotHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockParkingLotHistoryRepository)(nil).Insert), ctx, parkingLotHistory)
}
