// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repository/spot.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	model "github.com/bayu-gara/parking-lot/internal/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockSpotRepository is a mock of SpotRepository interface.
type MockSpotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSpotRepositoryMockRecorder
}

// MockSpotRepositoryMockRecorder is the mock recorder for MockSpotRepository.
type MockSpotRepositoryMockRecorder struct {
	mock *MockSpotRepository
}

// NewMockSpotRepository creates a new mock instance.
func NewMockSpotRepository(ctrl *gomock.Controller) *MockSpotRepository {
	mock := &MockSpotRepository{ctrl: ctrl}
	mock.recorder = &MockSpotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotRepository) EXPECT() *MockSpotRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockSpotRepository) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockSpotRepositoryMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockSpotRepository)(nil).BeginTx), ctx)
}

// FindAvailableSpotsByVehicleType mocks base method.
func (m *MockSpotRepository) FindAvailableSpotsByVehicleType(ctx context.Context, vehicleType model.VehicleType, limit int) ([]model.Spot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableSpotsByVehicleType", ctx, vehicleType, limit)
	ret0, _ := ret[0].([]model.Spot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableSpotsByVehicleType indicates an expected call of FindAvailableSpotsByVehicleType.
func (mr *MockSpotRepositoryMockRecorder) FindAvailableSpotsByVehicleType(ctx, vehicleType, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableSpotsByVehicleType", reflect.TypeOf((*MockSpotRepository)(nil).FindAvailableSpotsByVehicleType), ctx, vehicleType, limit)
}

// GetByID mocks base method.
func (m *MockSpotRepository) GetByID(ctx context.Context, id int64) (model.Spot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Spot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSpotRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSpotRepository)(nil).GetByID), ctx, id)
}

// Insert mocks base method.
func (m *MockSpotRepository) Insert(ctx context.Context, spot model.Spot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, spot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSpotRepositoryMockRecorder) Insert(ctx, spot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSpotRepository)(nil).Insert), ctx, spot)
}

// PopAvailableSpot mocks base method.
func (m *MockSpotRepository) PopAvailableSpot(ctx context.Context, vehicleType model.VehicleType) (model.Spot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopAvailableSpot", ctx, vehicleType)
	ret0, _ := ret[0].(model.Spot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PopAvailableSpot indicates an expected call of PopAvailableSpot.
func (mr *MockSpotRepositoryMockRecorder) PopAvailableSpot(ctx, vehicleType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopAvailableSpot", reflect.TypeOf((*MockSpotRepository)(nil).PopAvailableSpot), ctx, vehicleType)
}

// PushAvailableSpot mocks base method.
func (m *MockSpotRepository) PushAvailableSpot(ctx context.Context, spot model.Spot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushAvailableSpot", ctx, spot)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushAvailableSpot indicates an expected call of PushAvailableSpot.
func (mr *MockSpotRepositoryMockRecorder) PushAvailableSpot(ctx, spot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushAvailableSpot", reflect.TypeOf((*MockSpotRepository)(nil).PushAvailableSpot), ctx, spot)
}

// UpdateByOccupiedAndVehicleNumber mocks base method.
func (m *MockSpotRepository) UpdateByOccupiedAndVehicleNumber(ctx context.Context, id int64, isOccupied bool, vehicleNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByOccupiedAndVehicleNumber", ctx, id, isOccupied, vehicleNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByOccupiedAndVehicleNumber indicates an expected call of UpdateByOccupiedAndVehicleNumber.
func (mr *MockSpotRepositoryMockRecorder) UpdateByOccupiedAndVehicleNumber(ctx, id, isOccupied, vehicleNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByOccupiedAndVehicleNumber", reflect.TypeOf((*MockSpotRepository)(nil).UpdateByOccupiedAndVehicleNumber), ctx, id, isOccupied, vehicleNumber)
}

// UpsertSpot mocks base method.
func (m *MockSpotRepository) UpsertSpot(ctx context.Context, tx *sql.Tx, spot model.Spot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSpot", ctx, tx, spot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSpot indicates an expected call of UpsertSpot.
func (mr *MockSpotRepositoryMockRecorder) UpsertSpot(ctx, tx, spot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSpot", reflect.TypeOf((*MockSpotRepository)(nil).UpsertSpot), ctx, tx, spot)
}
